### PR TITLE
Fix select display bug when selecting rule and add clean functionality on template switch

### LINKED ISSUE #147: Schedule: not displaying correct information when updating rule
### Describe the bug

There are currently two very annoying bugs with this page.

One of them being the fact that if there is a select widget, then no selected information will be shown when editing a rule.
The other is that there is no clean up on contents after I switch templates, this can lead to bugs.

### Expected Behavior

- When I select a rule I want to see all information attached to it;
- When I select a different template for a rule it should clean all of its contents.

### Current Behavior

- Contents are being fetched but not displayed;
- No clean up is made.

### Reproduction Steps

1 - Go to schedule page
2 - Choose group
3 - Create rule
4 - Add basic information AND choose a temperature.

### Possible Solution

- Store information in an array and set default value in selects;
- Clean contents array after having changed template.

### Additional Information/Context

N/A

### PR DESCRIPTION
**Pull request by pdPinho**
### Issue

Closes #147 

### Reason for this change

It is very user-unfriendly to not display all the information contained within a rule - if a temperature or some other select widget had some value associated to it, then it should be displayed.

### Description of changes

- Fixed the fact that no select values were being selected in widgets that use `options` when trying to update a rule (fetch was happening but no display happened) 
- Fixed priority bug
- Added clean up functionality (clean contents array) on template switch (option)

### Description of how you validated changes

I created some rules and tested their behavior.

### Checklist
- [X] I have tested my changes locally.
- [ ] I have updated the documentation to reflect my changes.
- [ ] I have added/updated unit tests (if applicable).
- [X] My code adheres to the [CONTRIBUTING GUIDE](https://ua-smart-signage-platform.github.io/Documentation-Website/guidelines/)

### Aditional Information
N/A

### CODE REVIEW

File: frontend/src/pages/Schedule/index.jsx [hunk 1]
```diff
@@ -97,12 +104,24 @@ function Schedule(){
...
+            return rule
+        })
+
+        setRules(arr);
+        setChangesMade(true);
         setShowDeletePortal(false);
     }
 
+    console.log(rules);
+
```
Comment (fungame2270) [inline frontend/src/pages/Schedule/index.jsx]: log lost

**Review by fungame2270 — APPROVED** [review]
lgtm
