### PR TITLE
Frontend : fix some issues on user error using delete and chosing name of templates

### LINKED ISSUE #144: Frontend : Deleting Groups that have schedule crashs app
### Describe the bug

Deleting a group that is in use Crashs frontend

### Expected Behavior

Dont be able to delete group

### Current Behavior

You can click in delete Group but it Crashs the app

### Reproduction Steps

Delete a group that is in use in the schedule

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### PR DESCRIPTION
**Pull request by fungame2270**
### Issue

Closes #144.

### Reason for this change

this change makes the interface more robust to prevent user errors

### Description of changes

added modal to multiple pages warning ilegal actions in bd to the user.
Now if a group is being used in schedule it cant be deleted if a monitor is in a schedule it cant be changed of group.
In CCT now it checks if name is equal to other names of templates and only allows to save if the name is unique.

### Description of how you validated changes

tested locally

### Checklist
- [X] I have tested my changes locally.
- [ ] I have updated the documentation to reflect my changes.
- [ ] I have added/updated unit tests (if applicable).
- [X] My code adheres to the [CONTRIBUTING GUIDE](https://ua-smart-signage-platform.github.io/Documentation-Website/guidelines/)

### CODE REVIEW

**Comment by pdPinho** [comment]
Fix. PR. Title.

File: frontend/src/pages/Cct/index.jsx [hunk 1]
```diff
@@ -37,6 +41,10 @@ function Cct(){
         widgetService.getWidgets().then((response)=>{
             setWidgets(response.data)
         })
+        templateservice.getTemplates().then((response)=>{
+            console.log(response.data)
```
Comment (pdPinho) [inline frontend/src/pages/Cct/index.jsx]: remove console.log

File: frontend/src/pages/Cct/index.jsx [hunk 2]
```diff
@@ -127,6 +135,23 @@ function Cct(){
...
         }
     }
+
+    const handleNameChange = (e)=>{
+        let name = e.target.value
+        setName(name);
+        let unique = templates.every((element)=>{
+            return (element.name !== name || element.id === template.id)
+        })
+        console.log(unique)
```
Comment (pdPinho) [inline frontend/src/pages/Cct/index.jsx]: remove console.log

**Review by pdPinho — APPROVED** [review]
Change the things I asked for and fix sonarcloud issues and we're good to go :+1:
